import Foundation
import AppKit

@MainActor
public final class PasteManager {
    public static let shared = PasteManager()

    public static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    public init() {}

    public func copyTransient(text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()

        pb.setString(text, forType: .string)
        pb.setData(Data(), forType: Self.transientType)
        pb.setData(Data(), forType: Self.concealedType)
        pb.setData(Data(), forType: Self.autoGeneratedType)
    }

    public func paste(text: String, to targetApp: NSRunningApplication?) async {
        copyTransient(text: text)

        if let target = targetApp {
            target.activate()
            try? await Task.sleep(nanoseconds: 35_000_000) // 35ms
        }

        simulateCmdV()
    }

    public func simulateCmdV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let vKeyCode: CGKeyCode = 0x09 // 'v'

        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true)
        keyDown?.flags = .maskCommand

        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false)
        keyUp?.flags = .maskCommand

        keyDown?.post(tap: .cghidEventTap)
        keyUp?.post(tap: .cghidEventTap)
    }
}
